version: '3'
services:
  penground-db:
    container_name: penground-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: penground
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - penground-network
  penground-app:
    container_name: penground-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      penground-db:
        condition: service_started
    networks:
      - penground-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://penground-db:5432/penground
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
volumes:
  pgdata:

networks:
  penground-network: