openapi: 3.0.3
info:
  title: Penground API Specification
  description: |-
    Penground API exists for fun:
    - cryptography with fun
  version: 1.0-SNAPSHOT
servers:
  - url: '{domain}/api/v1'
    variables:
      domain:
        description: When deploy on same port / local
        default: http://localhost:8080
        enum:
          - http://localhost:8080
tags:
  - name: cryptography
    description: Perform fun encryption / decryption
paths:
  /cryptography/encrypt:
    post:
      tags:
        - cryptography
      summary: Encrypt by specifying algorithm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: EncryptionRequest
              allOf:
                - $ref: '#/components/schemas/CryptographyRequest'
                - type: object
              example:
                payload: hello world
                algorithm: LKH
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                title: EncryptionResponse
                allOf:
                  - $ref: '#/components/schemas/CryptographyResponse'
                  - type: object
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /cryptography/decrypt:
    post:
      tags:
        - cryptography
      summary: Decrypt by specifying algorithm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: DecryptionRequest
              allOf:
                - $ref: '#/components/schemas/CryptographyRequest'
                - type: object
              example:
                payload: YUdWc2JHOGdkMjl5YkdSS1MwTXdNU29x
                algorithm: LKH
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                title: DecryptionResponse
                allOf:
                  - $ref: '#/components/schemas/CryptographyResponse'
                  - type: object
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CryptographyRequest:
      type: object
      properties:
        payload:
          description: payload to encrypt
          type: string
        algorithm:
          $ref: '#/components/schemas/CryptographyAlgorithm'
      required:
        - payload
        - algorithm
    CryptographyAlgorithm:
      type: string
      enum:
        - LKH
        - SYS
    CryptographyResponse:
      type: object
      properties:
        payload:
          type: string
      required:
        - payload
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
      required:
        - error
        - message