server:
  port: 8080

spring:
  datasource:
#    #    url: jdbc:mysql://penground-db:3306/penground?allowPublicKeyRetrieval=true&useSSL=false     # docker-compose
#    url: jdbc:mysql://localhost:3306/penground?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:penground
    username: penguin
    password: playground
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # [dev only] config for create table by annotation
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
    console:
      path: /h2o
      settings.trace: false
      settings.web-allow-others: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoint:
    health:
      show-details: always