server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://penground-db:3306/penground?allowPublicKeyRetrieval=true&useSSL=false     # docker-compose
#    url: jdbc:mysql://localhost:3306/penground?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # [dev only] config for create table by annotation
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  endpoint:
    health:
      show-details: always