server:
  port: 8080

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/penground?allowPublicKeyRetrieval=true&useSSL=false}
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:password}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:penground
    username: penguin
    password: playground
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      # [dev only] config for create table by annotation
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true
    console:
      path: /h2o
      settings.trace: false
      settings.web-allow-others: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoint:
    health:
      show-details: always

cors:
  # -Pprod is still working as prod FE is on same port as BE, reserve for future FE BE independent
  allowedOrigins: http://localhost:3000