server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/penground}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      # [ddl-auto]
      # update – On application start-up, update the existing tables to match the schema Hibernate expects if necessary.
      # validate – On application start-up, check that the existing tables match the schema Hibernate expects, and throw an exception if they do not match.
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoint:
    health:
      show-details: always

cors:
  # -Pprod is still working as prod FE is on same port as BE, reserve for future FE BE independent
  allowedOrigins: http://localhost:3000

zonky.test.database.provider: Zonky